package com.globant.finanzaspersonales.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CAT_TDC".
 */
public class cat_tdc {

    private Long id;
    private long idUser;
    private String tdcName;
    private Float credit;
    private Float balance;
    private Integer active;

    public cat_tdc() {
    }

    public cat_tdc(Long id) {
        this.id = id;
    }

    public cat_tdc(Long id, long idUser, String tdcName, Float credit, Float balance, Integer active) {
        this.id = id;
        this.idUser = idUser;
        this.tdcName = tdcName;
        this.credit = credit;
        this.balance = balance;
        this.active = active;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getIdUser() {
        return idUser;
    }

    public void setIdUser(long idUser) {
        this.idUser = idUser;
    }

    public String getTdcName() {
        return tdcName;
    }

    public void setTdcName(String tdcName) {
        this.tdcName = tdcName;
    }

    public Float getCredit() {
        return credit;
    }

    public void setCredit(Float credit) {
        this.credit = credit;
    }

    public Float getBalance() {
        return balance;
    }

    public void setBalance(Float balance) {
        this.balance = balance;
    }

    public Integer getActive() {
        return active;
    }

    public void setActive(Integer active) {
        this.active = active;
    }

}
