package com.globant.finanzaspersonales.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CAT_CATEGORY".
 */
public class cat_category {

    private Long id;
    private Long idSonCategory;
    private String categoryName;
    private Integer active;

    public cat_category() {
    }

    public cat_category(Long id) {
        this.id = id;
    }

    public cat_category(Long id, Long idSonCategory, String categoryName, Integer active) {
        this.id = id;
        this.idSonCategory = idSonCategory;
        this.categoryName = categoryName;
        this.active = active;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIdSonCategory() {
        return idSonCategory;
    }

    public void setIdSonCategory(Long idSonCategory) {
        this.idSonCategory = idSonCategory;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public Integer getActive() {
        return active;
    }

    public void setActive(Integer active) {
        this.active = active;
    }

}
